### ISSUE TITLE
Solving issue with the height of cards for blog posts grid

### ISSUE THREAD

**Issue by xergioalex** [pereira-tech-talks/pereiratechtalks.com#103]
Check the Joan's pull request: https://github.com/pereira-tech-talks/pereiratechtalks.com/pull/96

![image](https://github.com/user-attachments/assets/e84a22ea-4f7c-4022-a695-9ced0b909b04)

**Comment by xergioalexpro** [comment]
@JoanSernaLeiton @arendondiosa the best way to solve this issue is using the `line-clamp` css style.

Take a look at this project in my repository: https://github.com/xergioalex/movies-page-css-grid

Here you can see how I solved that issue about the height of the cards:
![movies-css-grid](https://github.com/user-attachments/assets/1faab6e0-1b88-4972-aa96-81a786bdc536)
